
var OSH = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(OSH = {})  {

var e;e||(e=typeof OSH !== 'undefined' ? OSH : {});var aa,n;e.ready=new Promise((a,b)=>{aa=a;n=b});var ba=Object.assign({},e),q="./this.program",ca="object"==typeof window,r="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,t="",v,w,x;
if(da){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),ea=require("path");r?t=ea.dirname(t)+"/":t=require("url").fileURLToPath(new URL("./",import.meta.url));v=(b,c)=>{b=b.startsWith("file://")?new URL(b):ea.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};x=b=>{b=v(b,!0);b.buffer||(b=new Uint8Array(b));return b};w=(b,c,d,f=!0)=>{b=b.startsWith("file://")?new URL(b):ea.normalize(b);fs.readFile(b,f?void 0:"utf8",
(g,h)=>{g?d(g):c(f?h.buffer:h)})};!e.thisProgram&&1<process.argv.length&&(q=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);e.inspect=()=>"[Emscripten Module object]"}else if(ca||r)r?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),_scriptDir&&(t=_scriptDir),0!==t.indexOf("blob:")?t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):t="",v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},r&&(x=
a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),w=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var fa=e.print||console.log.bind(console),y=e.printErr||console.error.bind(console);Object.assign(e,ba);ba=null;e.thisProgram&&(q=e.thisProgram);var z;e.wasmBinary&&(z=e.wasmBinary);
var noExitRuntime=e.noExitRuntime||!0;"object"!=typeof WebAssembly&&A("no native wasm support detected");var B,ha=!1,C,D,E,F,G,H,I,K;function ia(){var a=B.buffer;e.HEAP8=C=new Int8Array(a);e.HEAP16=E=new Int16Array(a);e.HEAP32=G=new Int32Array(a);e.HEAPU8=D=new Uint8Array(a);e.HEAPU16=F=new Uint16Array(a);e.HEAPU32=H=new Uint32Array(a);e.HEAPF32=I=new Float32Array(a);e.HEAPF64=K=new Float64Array(a)}function ja(){var a=L();0==a&&(a+=4);H[a>>2]=34821223;H[a+4>>2]=2310721022;H[0]=1668509029}
function ka(){if(!ha){var a=L();0==a&&(a+=4);var b=H[a>>2],c=H[a+4>>2];34821223==b&&2310721022==c||A(`Stack overflow! Stack cookie has been overwritten at ${M(a)}, expected hex dwords 0x89BACDFE and 0x2135467, but received ${M(c)} ${M(b)}`);1668509029!=H[0]&&A("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var la=[],ma=[],na=[];function pa(){var a=e.preRun.shift();la.unshift(a)}var N=0,qa=null,O=null;
function A(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";y(a);ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");n(a);throw a;}function ra(a){return a.startsWith("data:application/octet-stream;base64,")}var P;if(e.locateFile){if(P="ffmpeg-h264.wasm",!ra(P)){var sa=P;P=e.locateFile?e.locateFile(sa,t):t+sa}}else P=(new URL("ffmpeg-h264.wasm",import.meta.url)).href;
function ta(a){try{if(a==P&&z)return new Uint8Array(z);if(x)return x(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}function ua(a){if(!z&&(ca||r)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ta(a));if(w)return new Promise((b,c)=>{w(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>ta(a))}
function va(a,b,c){return ua(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{y("failed to asynchronously prepare wasm: "+d);A(d)})}
function wa(a,b){var c=P;return z||"function"!=typeof WebAssembly.instantiateStreaming||ra(c)||c.startsWith("file://")||da||"function"!=typeof fetch?va(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){y("wasm streaming compile failed: "+f);y("falling back to ArrayBuffer instantiation");return va(c,a,b)}))}var Q,R;function xa(a){for(;0<a.length;)a.shift()(e)}function M(a){return"0x"+a.toString(16).padStart(8,"0")}
var ya="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function Aa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError(`Unknown type size: ${a}`);}}var Ba=void 0;function S(a){for(var b="";D[a];)b+=Ba[D[a++]];return b}var Ca={},Da={},Ea={};function Fa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a}function Ga(a,b){a=Fa(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Ha(a){var b=Error,c=Ga(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c}var Ia=void 0;function T(a){throw new Ia(a);}
function U(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T(`type "${d}" must have a positive integer typeid pointer`);if(Da.hasOwnProperty(a)){if(c.Z)return;T(`Cannot register type '${d}' twice`)}Da[a]=b;delete Ea[a];Ca.hasOwnProperty(a)&&(b=Ca[a],delete Ca[a],b.forEach(f=>f()))}
var V=new function(){this.K=[void 0];this.V=[];this.get=function(a){return this.K[a]};this.has=function(a){return void 0!==this.K[a]};this.X=function(a){var b=this.V.pop()||this.K.length;this.K[b]=a;return b};this.Y=function(a){this.K[a]=void 0;this.V.push(a)}},Ja=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return V.X({$:1,value:a})}};function Ka(a){return this.fromWireType(G[a>>2])}
function La(a,b){switch(b){case 2:return function(c){return this.fromWireType(I[c>>2])};case 3:return function(c){return this.fromWireType(K[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Ma(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return D[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return F[d>>1]};case 2:return c?function(d){return G[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
function Na(a,b,c){var d=D;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}
function Oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var Pa="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function Qa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&F[c];)++c;c<<=1;if(32<c-a&&Pa)return Pa.decode(D.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var f=E[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}
function Ra(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)E[b>>1]=a.charCodeAt(f),b+=2;E[b>>1]=0;return b-d}function Sa(a){return 2*a.length}function Ta(a,b){for(var c=0,d="";!(c>=b/4);){var f=G[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}
function Ua(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}G[b>>2]=g;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d}function Va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Wa={};
function Xa(){if(!Ya){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:q||"./this.program"},b;for(b in Wa)void 0===Wa[b]?delete a[b]:a[b]=Wa[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ya=c}return Ya}var Ya,Za=[null,[],[]];function $a(a,b){C.set(a,b)}for(var ab=Array(256),X=0;256>X;++X)ab[X]=String.fromCharCode(X);Ba=ab;Ia=e.BindingError=Ha("BindingError");
e.InternalError=Ha("InternalError");V.K.push({value:void 0},{value:null},{value:!0},{value:!1});V.W=V.K.length;e.count_emval_handles=function(){for(var a=0,b=V.W;b<V.K.length;++b)void 0!==V.K[b]&&++a;return a};
var db={a:function(a){a>>>=0;var b=bb(),c=L();A(`stack overflow (Attempt to set SP to ${M(a)}`+`, with stack limits [${M(c)} - ${M(b)}`+"]). If you require more stack space build with -sSTACK_SIZE=<bytes>")},q:function(){return 0},r:function(){},o:function(){},v:function(a,b,c,d,f){var g=Aa(c);b=S(b);U(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var k=C;else if(2===c)k=E;else if(4===c)k=G;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(k[h>>g])},U:null})},m:function(a,b){b=S(b);U(a,{name:b,fromWireType:function(c){c||T("Cannot use deleted val. handle = "+c);var d=V.get(c).value;c>=V.W&&0===--V.get(c).$&&V.Y(c);return d},toWireType:function(c,d){return Ja(d)},argPackAdvance:8,readValueFromPointer:Ka,U:null})},h:function(a,b,c){c=Aa(c);b=S(b);U(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){return f},argPackAdvance:8,readValueFromPointer:La(b,c),U:null})},d:function(a,b,c,d,f){b=
S(b);-1===f&&(f=4294967295);f=Aa(c);var g=k=>k;if(0===d){var h=32-8*c;g=k=>k<<h>>>h}c=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,m){return m};U(a,{name:b,fromWireType:g,toWireType:c,argPackAdvance:8,readValueFromPointer:Ma(b,f,0!==d),U:null})},c:function(a,b,c){function d(g){g>>=2;var h=H;return new f(h.buffer,h[g+1],h[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);U(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},
{Z:!0})},g:function(a,b){b=S(b);var c="std::string"===b;U(a,{name:b,fromWireType:function(d){var f=H[d>>2],g=d+4;if(c)for(var h=g,k=0;k<=f;++k){var m=g+k;if(k==f||0==D[m]){h=h?za(D,h,m-h):"";if(void 0===l)var l=h;else l+=String.fromCharCode(0),l+=h;h=m+1}}else{l=Array(f);for(k=0;k<f;++k)l[k]=String.fromCharCode(D[g+k]);l=l.join("")}Y(d);return l},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"==typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||
f instanceof Int8Array||T("Cannot pass non-string to std::string");var h=c&&g?Oa(f):f.length;var k=cb(4+h+1),m=k+4;H[k>>2]=h;if(c&&g)Na(f,m,h+1);else if(g)for(g=0;g<h;++g){var l=f.charCodeAt(g);255<l&&(Y(m),T("String has UTF-16 code units that do not fit in 8 bits"));D[m+g]=l}else for(g=0;g<h;++g)D[m+g]=f[g];null!==d&&d.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:Ka,U:function(d){Y(d)}})},e:function(a,b,c){c=S(c);if(2===b){var d=Qa;var f=Ra;var g=Sa;var h=()=>F;var k=1}else 4===b&&(d=
Ta,f=Ua,g=Va,h=()=>H,k=2);U(a,{name:c,fromWireType:function(m){for(var l=H[m>>2],p=h(),u,J=m+4,W=0;W<=l;++W){var oa=m+4+W*b;if(W==l||0==p[oa>>k])J=d(J,oa-J),void 0===u?u=J:(u+=String.fromCharCode(0),u+=J),J=oa+b}Y(m);return u},toWireType:function(m,l){"string"!=typeof l&&T(`Cannot pass non-string to C++ string type ${c}`);var p=g(l),u=cb(4+p+b);H[u>>2]=p>>k;f(l,u+4,p+b);null!==m&&m.push(Y,u);return u},argPackAdvance:8,readValueFromPointer:Ka,U:function(m){Y(m)}})},w:function(a,b){b=S(b);U(a,{aa:!0,
name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},b:function(){A("")},f:function(){return Date.now()},l:function(a,b,c){D.copyWithin(a,b,b+c)},k:function(a){var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);a:{f=f.min.call(f,2147483648,d+(65536-d%65536)%65536)-B.buffer.byteLength+65535>>>16;try{B.grow(f);ia();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},s:function(a,b){var c=
0;Xa().forEach(function(d,f){var g=b+c;f=H[a+4*f>>2]=g;for(g=0;g<d.length;++g)C[f++>>0]=d.charCodeAt(g);C[f>>0]=0;c+=d.length+1});return 0},t:function(a,b){var c=Xa();H[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});H[b>>2]=d;return 0},j:function(){return 52},u:function(a,b){var c=0;if(0==a)c=2;else if(1==a||2==a)c=64;C[b>>0]=2;E[b+2>>1]=1;R=[c>>>0,(Q=c,1<=+Math.abs(Q)?0<Q?+Math.floor(Q/4294967296)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];G[b+8>>2]=R[0];G[b+12>>2]=R[1];R=
[0,(Q=0,1<=+Math.abs(Q)?0<Q?+Math.floor(Q/4294967296)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];G[b+16>>2]=R[0];G[b+20>>2]=R[1];return 0},p:function(){return 52},n:function(){return 70},i:function(a,b,c,d){for(var f=0,g=0;g<c;g++){var h=H[b>>2],k=H[b+4>>2];b+=8;for(var m=0;m<k;m++){var l=D[h+m],p=Za[a];0===l||10===l?((1===a?fa:y)(za(p,0)),p.length=0):p.push(l)}f+=k}H[d>>2]=f;return 0}};
(function(){function a(c){c=c.exports;e.asm=c;B=e.asm.x;ia();ma.unshift(e.asm.y);N--;e.monitorRunDependencies&&e.monitorRunDependencies(N);if(0==N&&(null!==qa&&(clearInterval(qa),qa=null),O)){var d=O;O=null;d()}return c}var b={a:db};N++;e.monitorRunDependencies&&e.monitorRunDependencies(N);if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(c){y("Module.instantiateWasm callback failed with error: "+c),n(c)}wa(b,function(c){a(c.instance)}).catch(n);return{}})();
e._av_get_default_channel_layout=function(){return(e._av_get_default_channel_layout=e.asm.z).apply(null,arguments)};e._av_frame_alloc=function(){return(e._av_frame_alloc=e.asm.A).apply(null,arguments)};e._avcodec_find_decoder_by_name=function(){return(e._avcodec_find_decoder_by_name=e.asm.B).apply(null,arguments)};e._avcodec_open2=function(){return(e._avcodec_open2=e.asm.C).apply(null,arguments)};e._avcodec_flush_buffers=function(){return(e._avcodec_flush_buffers=e.asm.D).apply(null,arguments)};
e._av_init_packet=function(){return(e._av_init_packet=e.asm.E).apply(null,arguments)};e._av_packet_from_data=function(){return(e._av_packet_from_data=e.asm.F).apply(null,arguments)};e._avcodec_send_packet=function(){return(e._avcodec_send_packet=e.asm.G).apply(null,arguments)};e._avcodec_receive_frame=function(){return(e._avcodec_receive_frame=e.asm.H).apply(null,arguments)};e._avcodec_alloc_context3=function(){return(e._avcodec_alloc_context3=e.asm.I).apply(null,arguments)};
e.__embind_initialize_bindings=function(){return(e.__embind_initialize_bindings=e.asm.J).apply(null,arguments)};var cb=e._malloc=function(){return(cb=e._malloc=e.asm.L).apply(null,arguments)};function Y(){return(Y=e.asm.M).apply(null,arguments)}function eb(){return(eb=e.asm.N).apply(null,arguments)}function bb(){return(bb=e.asm.O).apply(null,arguments)}function L(){return(L=e.asm.P).apply(null,arguments)}function fb(){return(fb=e.asm.Q).apply(null,arguments)}
function gb(){return(gb=e.asm.R).apply(null,arguments)}function hb(){return(hb=e.asm.S).apply(null,arguments)}var ib=e.___set_stack_limits=function(){return(ib=e.___set_stack_limits=e.asm.T).apply(null,arguments)};e._ff_h264_cabac_tables=146372;
e.ccall=function(a,b,c,d){var f={string:l=>{var p=0;if(null!==l&&void 0!==l&&0!==l){p=Oa(l)+1;var u=hb(p);Na(l,u,p);p=u}return p},array:l=>{var p=hb(l.length);$a(l,p);return p}};a=e["_"+a];var g=[],h=0;if(d)for(var k=0;k<d.length;k++){var m=f[c[k]];m?(0===h&&(h=fb()),g[k]=m(d[k])):g[k]=d[k]}c=a.apply(null,g);return c=function(l){0!==h&&gb(h);return"string"===b?l?za(D,l):"":"boolean"===b?!!l:l}(c)};
e.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":C[a>>0]=b;break;case "i8":C[a>>0]=b;break;case "i16":E[a>>1]=b;break;case "i32":G[a>>2]=b;break;case "i64":A("to do setValue(i64) use WASM_BIGINT");case "float":I[a>>2]=b;break;case "double":K[a>>3]=b;break;case "*":H[a>>2]=b;break;default:A(`invalid type for setValue: ${c}`)}};
e.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return C[a>>0];case "i8":return C[a>>0];case "i16":return E[a>>1];case "i32":return G[a>>2];case "i64":A("to do getValue(i64) use WASM_BIGINT");case "float":return I[a>>2];case "double":return K[a>>3];case "*":return H[a>>2];default:A(`invalid type for getValue: ${b}`)}};e.writeArrayToMemory=$a;var Z;O=function jb(){Z||kb();Z||(O=jb)};
function kb(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!ha)){ka();var b=bb(),c=L();ib(b,c);xa(ma);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();ka();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),na.unshift(b);xa(na)}}if(!(0<N)){eb();ja();if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)pa();xa(la);0<N||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a(),ka())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();kb();


  return OSH.ready
}

);
})();
export default OSH;